### ISSUE TITLE
Dropdown scrollbar

### ISSUE THREAD

**Issue by zvasic** [running-coder/jquery-typeahead#125]
Is it possible to add scroll bar in result container and make results (rows) scrollable when browsing through results on keyboard?

**Comment by running-coder** [comment]
sure.. simply add some css

``` css
.typeahead-list {
    max-height: 300px;
    overflow-y: scroll;
}
```
