### ISSUE TITLE
Issue with typeahead input when used with Bootstrap

### ISSUE THREAD

**Issue by tawalters61** [running-coder/jquery-typeahead#128]
Hi,

I am having an issue using typeahead with Bootstrap. The 'x' is not appearing on the 'input' to allow the current search text to be deleted. I copied the source from the website demo and it works fine, but if I include the Bootstrap CSS and JS files, the problem occurs.

**Comment by running-coder** [comment]
Bootstrap overrides some of the default browser behaviors... find this line and remove it

``` css
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
}
```
