### ISSUE TITLE
where is the little x to clear the input field ?

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#161]
When I try one of the demonstration examples in my project everything works perfectly but when I combine it with the latest bootstrap version then the little x to clear the input field is no longer visible.

this is my index file 

<!DOCTYPE html>
<html ng-app="myApp">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        
        <link rel="icon" href="img/favicon.ico">

        <title>My Project</title>

        <link type="text/css" rel="stylesheet" href="css/bootstrap.css">
        <link type="text/css" rel="stylesheet" href="css/jquery.typeahead.css">
        <link type="text/css" rel="stylesheet" href="css/theme.css">
        
    </head>

    <body>
         
          ....
        
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular-resource.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.18/angular-ui-router.min.js"></script>

        <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
        
        <script src="js/bootstrap/bootstrap.js"></script>
        <script src="js/bootstrap/jquery.typeahead.js"></script>
   
    </body>

</html>

when i remove the line 

<link type="text/css" rel="stylesheet" href="css/bootstrap.css">

everything works fine

I use bootstrap 3.3.6 + JQuery Typeahead 2.3.4

Is this a known issue ?

**Comment by running-coder** [comment]
hey,

it is from the bootstrap styles if I remember correctly, try removing

``` css
input[type="search"] {
  -webkit-box-sizing: content-box;
     -moz-box-sizing: content-box;
          box-sizing: content-box;
  -webkit-appearance: textfield;
}
```

**Comment by running-coder** [comment]
Also refers to #128

**Comment by running-coder** [comment]
Added
``` css
.typeahead-field input[type="search"]::-webkit-search-cancel-button {
  /*Bootstrap 3 override*/
  -webkit-appearance: searchfield-cancel-button;
}
```

Works in Chrome and IE, not Firefox
