### ISSUE TITLE
how to skin the new cancel button through CSS

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#196]
Hello again,

The new cancel button is positioned outside the input box, too much to the right and a little too low.
How can I set the padding, width, color,... through CSS

Thx again :-)

**Comment by running-coder** [comment]
Hey, are you familiar with CSS? you can edit the scss file and recompile using `gulp` command but I wouldn't recommend that since the scss file might change in the future and it will be harder for you to upgrade later on. I would recommend using a simple css file that overrides specific typeahead classes. For example:

```css
// typeaheadOverride.css
.myTypeahead .typeahead__cancel-button {
   top: 10px;
   right: 10px;
}
```
