### ISSUE TITLE
rounded corners on mobile browsers

### ISSUE THREAD

**Issue by nicholaide** [running-coder/jquery-typeahead#236]
When viewed on a mobile browser (in my case, Safari or Chrome in ios), the [demos](http://www.runningcoder.org/jquerytypeahead/demo/) all have rounded corners. As you type, the input field's borders alternate between round and square. 

Is this a known issue with mobile browsers? Where should we look if we want to address this?

**Comment by davidutzus** [comment]
for me a quick fix was:
```css
.typeahead__container [type=search] {
    -webkit-appearance: none !important;
}

.typeahead__field input[type=search]::-webkit-search-cancel-button {
    -webkit-appearance: none !important;
    appearance: none !important;
}
```
[-moz-appearance (-webkit-appearance) = Non-standard](https://developer.mozilla.org/en/docs/Web/CSS/-moz-appearance)
