### ISSUE TITLE
Width of results field

### ISSUE THREAD

**Issue by sebaOnGitHub** [running-coder/jquery-typeahead#492]
How can i make results field wider than parent (input selector) ?

**Comment by tombertrand** [comment]
that sounds like a simple css solution, you can define your own selector for `typeahead__list` inside the configuration or extend it
```css
.typeahead__list {
  width: 110%;
}
```
