### ISSUE TITLE
Global template for dropdown

### ISSUE THREAD

**Issue by ivanilinov** [running-coder/jquery-typeahead#69]
How can i specify **global** template for dropdown?
For example: several sources in multicolumn (or table) layout.

```html
<table>
<tr>
<td>{{list_from_source_1}}</td>
<td>{{list_from_source_2}}</td>
</tr>
</table>
```

**Comment by ivanilinov** [comment]
Hi! You do not plan to implement this feature?

**Comment by running-coder** [comment]
hey Ivan sry for the confusion, pretty sure what you are looking for can be acheived with css using width percentages for `<li>` instead of being 100% they could be 50% (and the last one 100%)

```css
.typeahead__dropdown {
    width: 230px;
}

.typeahead__dropdown-item.conference-western,
.typeahead__dropdown-item.conference-eastern {
    width: 50%;
    display:inline-block;
}
```

![hockey](https://cloud.githubusercontent.com/assets/7377382/14286705/0226b33c-fb1e-11e5-90b5-c5761a80a810.jpg)
